version: "3.4"
services:
  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-db-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PG_TRUST_LOCALNET
    networks:
      backend: { aliases: [postgres.backend] }

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: university/server
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - app-logs:/usr/local/tomcat/logs
    networks:
      backend: { aliases: [app.backend] }

networks:
  backend:
    driver: bridge

volumes:
  postgres-db-data:
  app-logs:
